import:
  - ./.gruvbox.yml

font:
  normal:
    family: mononoki Nerd Font Mono
  # size: 18  # stream
  size: 16 # comfy
  # size: 14  # dense

# shell:
#   program: /usr/local/bin/fish
#   args:
#     - --login

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
