import:
  - ./.kanagawa.yml

font:
  normal:
    family: mononoki Nerd Font Mono
  # size: 22 # streaming
  # size: 18 # comfy
  size: 14 # working

shell:
  program: /usr/bin/fish
  args:
    - --login
