import:
  # - ./.gruvbox.yml
  # - ./.tokyonight_moon.yml
  - ./.kanagawa.yml

font:
  normal:
    family: mononoki Nerd Font Mono
  # size: 18
  # size: 16
  # size: 14
  size: 12

shell:
  program: /usr/bin/fish
  args:
    - --login
